const PARTS = {
  NOSE_CONE: {
    id: 'NOSE_CONE',
    name: 'Nose Cone',
    description: 'Aerodynamic nose cone, reduces drag',
    mass: 0.3,
    dragCoeff: 0.05,
    width: 1,
    height: 1.5,
    cost: 200,
    tech: 0,
    type: 'structural',
    color: '#cc4444',
    shape: 'triangle',
    stackable: false,
  },

  NOSE_CONE_POINTY: {
    id: 'NOSE_CONE_POINTY',
    name: 'Pointy Nose Cone',
    description: 'Extra aerodynamic, very low drag',
    mass: 0.25,
    dragCoeff: 0.02,
    width: 1,
    height: 2,
    cost: 350,
    tech: 1,
    type: 'structural',
    color: '#dd6633',
    shape: 'triangle',
    stackable: false,
  },

  FUEL_TANK_S: {
    id: 'FUEL_TANK_S',
    name: 'Small Fuel Tank',
    description: 'Holds 50 units of fuel',
    mass: 0.4,
    dryMass: 0.15,
    fuelCapacity: 50,
    dragCoeff: 0.3,
    width: 1,
    height: 1,
    cost: 300,
    tech: 0,
    type: 'fuel',
    fuelType: 'kerosene',
    color: '#cccccc',
    shape: 'rectangle',
    stackable: true,
  },

  FUEL_TANK_M: {
    id: 'FUEL_TANK_M',
    name: 'Medium Fuel Tank',
    description: 'Holds 150 units of fuel',
    mass: 0.9,
    dryMass: 0.35,
    fuelCapacity: 150,
    dragCoeff: 0.3,
    width: 1,
    height: 2,
    cost: 600,
    tech: 0,
    type: 'fuel',
    fuelType: 'kerosene',
    color: '#bbbbbb',
    shape: 'rectangle',
    stackable: true,
  },

  FUEL_TANK_L: {
    id: 'FUEL_TANK_L',
    name: 'Large Fuel Tank',
    description: 'Holds 400 units of fuel',
    mass: 2.2,
    dryMass: 0.8,
    fuelCapacity: 400,
    dragCoeff: 0.3,
    width: 1,
    height: 3,
    cost: 1200,
    tech: 1,
    type: 'fuel',
    fuelType: 'kerosene',
    color: '#aaaaaa',
    shape: 'rectangle',
    stackable: true,
  },

  ENGINE_S: {
    id: 'ENGINE_S',
    name: 'Small Engine',
    description: 'Basic engine, 80kN thrust',
    mass: 0.5,
    thrust: 80000,
    fuelConsumption: 3,
    dragCoeff: 0.4,
    width: 1,
    height: 0.8,
    cost: 500,
    tech: 0,
    type: 'engine',
    fuelType: 'kerosene',
    color: '#555555',
    shape: 'trapezoid',
    nozzleColor: '#333333',
    gimbalRange: 3,
    stackable: false,
  },

  ENGINE_M: {
    id: 'ENGINE_M',
    name: 'Medium Engine',
    description: 'Reliable engine, 250kN thrust',
    mass: 1.2,
    thrust: 250000,
    fuelConsumption: 8,
    dragCoeff: 0.4,
    width: 1,
    height: 1.2,
    cost: 1200,
    tech: 0,
    type: 'engine',
    fuelType: 'kerosene',
    color: '#555555',
    shape: 'trapezoid',
    nozzleColor: '#333333',
    gimbalRange: 5,
    stackable: false,
  },

  ENGINE_L: {
    id: 'ENGINE_L',
    name: 'Large Engine',
    description: 'Powerful engine, 600kN thrust',
    mass: 3.0,
    thrust: 600000,
    fuelConsumption: 20,
    dragCoeff: 0.5,
    width: 1,
    height: 1.8,
    cost: 3000,
    tech: 1,
    type: 'engine',
    fuelType: 'kerosene',
    color: '#444444',
    shape: 'trapezoid',
    nozzleColor: '#222222',
    gimbalRange: 4,
    stackable: false,
  },

  ENGINE_VAC: {
    id: 'ENGINE_VAC',
    name: 'Vacuum Engine',
    description: 'High efficiency in vacuum, 180kN',
    mass: 1.0,
    thrust: 180000,
    fuelConsumption: 4,
    dragCoeff: 0.4,
    width: 1,
    height: 1.5,
    cost: 2500,
    tech: 2,
    type: 'engine',
    fuelType: 'kerosene',
    color: '#556677',
    shape: 'trapezoid',
    nozzleColor: '#334455',
    gimbalRange: 2,
    vacuumOptimized: true,
    stackable: false,
  },

  SEPARATOR: {
    id: 'SEPARATOR',
    name: 'Stage Separator',
    description: 'Separates stages when activated',
    mass: 0.1,
    dragCoeff: 0.1,
    width: 0.8,
    height: 0.3,
    cost: 150,
    tech: 0,
    type: 'structural',
    color: '#888888',
    shape: 'separator',
    stackable: true,
  },

  PARACHUTE: {
    id: 'PARACHUTE',
    name: 'Parachute',
    description: 'Deploys to slow descent in atmosphere',
    mass: 0.3,
    dragCoeff: 0.1,
    deployedDrag: 8.0,
    width: 1,
    height: 0.5,
    cost: 400,
    tech: 0,
    type: 'parachute',
    color: '#ff4444',
    shape: 'rectangle',
    deployable: true,
    stackable: false,
  },

  LANDING_LEG: {
    id: 'LANDING_LEG',
    name: 'Landing Legs',
    description: 'Deployable legs for landing',
    mass: 0.4,
    dragCoeff: 0.2,
    width: 1.5,
    height: 0.3,
    cost: 500,
    tech: 1,
    type: 'landing_leg',
    color: '#777777',
    shape: 'legs',
    deployable: true,
    stackable: false,
  },

  RCS_BLOCK: {
    id: 'RCS_BLOCK',
    name: 'RCS Thruster Block',
    description: 'Four small thrusters for attitude control',
    mass: 0.2,
    thrust: 2000,
    fuelConsumption: 0.3,
    dragCoeff: 0.15,
    width: 1,
    height: 0.4,
    cost: 800,
    tech: 2,
    type: 'rcs',
    color: '#667788',
    shape: 'rectangle',
    stackable: true,
  },

  BATTERY: {
    id: 'BATTERY',
    name: 'Battery Pack',
    description: 'Stores electrical charge for systems',
    mass: 0.3,
    dragCoeff: 0.2,
    width: 1,
    height: 0.6,
    cost: 350,
    tech: 1,
    type: 'battery',
    color: '#ffcc00',
    shape: 'rectangle',
    stackable: true,
  },

  SOLAR_PANEL: {
    id: 'SOLAR_PANEL',
    name: 'Solar Panel',
    description: 'Generates power from sunlight',
    mass: 0.2,
    dragCoeff: 0.5,
    width: 1.5,
    height: 0.2,
    cost: 600,
    tech: 2,
    type: 'solar',
    color: '#2244aa',
    shape: 'panel',
    deployable: true,
    stackable: false,
  },

  HEAT_SHIELD: {
    id: 'HEAT_SHIELD',
    name: 'Heat Shield',
    description: 'Protects from reentry heating',
    mass: 0.8,
    dragCoeff: 0.6,
    width: 1.3,
    height: 0.2,
    cost: 700,
    tech: 2,
    type: 'heatshield',
    color: '#553322',
    shape: 'rectangle',
    stackable: false,
  },

  PROBE: {
    id: 'PROBE',
    name: 'Probe Core',
    description: 'Unmanned control module',
    mass: 0.1,
    dragCoeff: 0.15,
    width: 0.8,
    height: 0.4,
    cost: 400,
    tech: 1,
    type: 'probe',
    color: '#446688',
    shape: 'rectangle',
    electricPotential: 50,
    stackable: false,
  },

  CARGO_BAY: {
    id: 'CARGO_BAY',
    name: 'Cargo Bay',
    description: 'Store payloads and cargo',
    mass: 0.5,
    dragCoeff: 0.2,
    width: 1,
    height: 1.5,
    cost: 900,
    tech: 2,
    type: 'cargo',
    color: '#668899',
    shape: 'rectangle',
    stackable: true,
  },

  FUEL_TANK_HYDROGEN: {
    id: 'FUEL_TANK_HYDROGEN',
    name: 'Hydrogen Fuel Tank',
    description: 'Lightweight, holds 200 units of hydrogen',
    mass: 0.6,
    dryMass: 0.4,
    fuelCapacity: 200,
    dragCoeff: 0.3,
    width: 1,
    height: 2.5,
    cost: 1500,
    tech: 3,
    type: 'fuel',
    fuelType: 'hydrogen',
    color: '#aaccdd',
    shape: 'rectangle',
    stackable: true,
  },

  ENGINE_HYDROGEN: {
    id: 'ENGINE_HYDROGEN',
    name: 'Hydrogen Engine',
    description: 'High efficiency hydrogen engine, 150kN',
    mass: 1.5,
    thrust: 150000,
    fuelConsumption: 2.5,
    dragCoeff: 0.4,
    width: 1,
    height: 1.5,
    cost: 4000,
    tech: 3,
    type: 'engine',
    fuelType: 'hydrogen',
    color: '#88aacc',
    shape: 'trapezoid',
    nozzleColor: '#557799',
    gimbalRange: 3,
    stackable: false,
  },
};

function getPart(id) {
  return PARTS[id] ? { ...PARTS[id] } : null;
}

function getPartsByTech(level) {
  return Object.values(PARTS).filter(p => p.tech <= level);
}

function getPartsByType(type) {
  return Object.values(PARTS).filter(p => p.type === type);
}

const PART_CATEGORIES = [
  { name: 'Structural', types: ['structural', 'heatshield', 'probe', 'cargo'] },
  { name: 'Fuel Tanks', types: ['fuel'] },
  { name: 'Engines', types: ['engine'] },
  { name: 'Aerodynamics', types: ['parachute'] },
  { name: 'Control', types: ['rcs', 'battery', 'solar'] },
  { name: 'Landing', types: ['landing_leg'] },
];
